# Generated by Django 3.2.18 on 2023-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=2, error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, max_length=10),
            preserve_default=False,
        ),
    ]
