# Generated by Django 3.2.18 on 2023-06-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, max_length=10, null=True),
        ),
    ]
